apiVersion: v1
kind: Service
metadata:
  name: kvs-headless
  namespace: kvs
spec:
  type: ClusterIP
  clusterIP: None # Allocate no virtual IP so DNS records point straight to pods
  selector:
    app.kubernetes.io/name: kvs
  ports:
    - port: 3000       # The port the Service listens on inside the cluster
      targetPort: http # The port the container inside the Pod is running on
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: kvs
  namespace: kvs
spec:
  type: ClusterIP
  # Omit clusterIP so that it gets auto-assigned
  selector:
    app.kubernetes.io/name: kvs
  ports:
    - port: 3000
      targetPort: http
      name: http
